baseURL = "/"
languageCode = "ru"
title = "Портфолио технического писателя"
theme = ""
paginate = 10

[params]
  author = "Иван Петров"
  tagline = "Технический писатель — документация, гайды, руководства"

